name: Create Branch on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Issue Number
        id: extract
        run: echo "::set-output name=issue_number::${{ github.event.issue.number }}"

      - name: Create Branch
        run: |
          git checkout -b issue/${{ steps.extract.outputs.issue_number }}
          git push origin issue/${{ steps.extract.outputs.issue_number }}

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v2
        with:
            server_address: smtp.gmail.com
            server_port: 587
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: 'GitHub Issue Assigned'
            body: 'A GitHub issue has been assigned to you. Please proceed with Domino Workspace creation using branch issue/${{ steps.extract.outputs.issue_number }}'
            from: mailer@ksmpartners.com
            to: ${{ github.event.issue.assignee.login }}
