name: Create Pull Request on Issue Branch

on:
  push:
    branches:
      - 'issue/**'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest     
    steps:
      - name: Create Pull Request
        run: gh pr create -B main -H ${{ github.ref }} --title 'Merge ${{ github.ref }} into main' --body 'Created by GitHub action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Send Email Notification
      #   env:
      #     EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      #     EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #       server_address: smtp.gmail.com
      #       server_port: 465
      #       secure: true
            # ignore_cert: true
            # username: $EMAIL_USERNAME
            # password: $EMAIL_PASSWORD
            # subject: 'GitHub Issue Assigned'
            # body: 'A GitHub issue has been assigned to you. Please proceed with Domino Workspace creation using branch issue/${{ steps.extract.outputs.issue_number }}'
            # from: mailer@ksmpartners.com
            # to: ${{ github.event.issue.assignee.login }}
