name: Create Pull Request on Issue Branch

on:
  push:
    branches:
      - 'issue/**'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest     
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Pull Request
        run: |
          git checkout -b ${{ github.ref }}
          gh pr create -B main -H ${{ github.ref }} --title 'Merge ${{ github.ref }} into main' --body 'Created by GitHub action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
